### PR TITLE
Eslint and editorsconfig changes.

### PR DESCRIPTION
**Pull request by bafxyz**

### CODE REVIEW

**Comment by rodislav** [comment]
hi, I'll take a look at pull request, later this day

**Comment by rodislav** [comment]
so, I agree with 99% of the changes, the only thing I would like to discuss more, is the position of the { (open curly brace) I still find it much easier to read code when curly brace is on next line, since it always enforce a new line, so function header is always visible.

what do you think ? @bafxyz and @websoftwares

**Comment by rodislav** [comment]
Why merged ? :-(

**Comment by websoftwares** [comment]
Yea why?:(

**Pull request merged**
